### PR TITLE
v3

### PR DESCRIPTION
**Pull request by kaisermann**
agadoo

1. BREAKING CHANGE: Changes completely the API. Now, to format a number, date or time, the
developer must explicitly import the formatter store:

`import { time, date, number } from 'svelte-i18n'`

2. BREAKING CHANGE: It's now needed to explicitly import the `getClientLocale` method to use
its heuristics when setting the initial locale. This makes the method
and its helpers to be tree-shakeable.

```js
import { init, getClientLocale } from 'svelte-i18n'

init({
    initialLocale: getClientLocale({ ... })
})
```

> Since `v2` is very recent, releasing `v3` soon-ish can make the project look not trustworthy, but I'll try fixing any bugs found in `v2` when that moment arrives 😁.

### CODE REVIEW

**Comment by elbourki** [comment]
Hey! That's a pretty awesome package you got there!

What if we removed `getClientLocale` from utils and made it 100% optional? We could do that by making `initialLocale` accept an array of _ISO_ codes and it finds the first one that has registered translations... I think this way it would allow developers to use external libraries like _wojtekmaj/get-user-locale_, they offer a pretty handy method called `getUserLocales` that returns an array as well, so this means you won't have to maintain that functionality and developers would have more flexibility.

And please let me know if you have a to do list or something, I can help with some tasks :)

**Comment by kaisermann** [comment]
@elbourki hey 😁! That's a great idea! I'll take a look at it whenever I can. In this PR, the `getClientLocale` is already optional because it gets tree-shaked if you don't use it. 

I don't really have a to-do list for this version, but it started as a movement to make the lib smaller by removing some unneeded utilities and make others tree-shakeable. I was looking into trying to compile the dictionary so we could ditch the `intl-messageformat`, but I currently don't have enough time available to tackle that (and I'm afraid it would make the lib a bit more cumbersome to use, but just a bit). There's also issue #45, which I also didn't have time yet to check if it's valid and would make sense to implement. Anyway, any help on any discussed topic is highly appreciated 😁

**Comment by kaisermann** [comment]
I became kind of a hostage of npm when I tried to launch a `alpha` version 🤷‍♂ Released `v3` now. Unfortunately, without much weight loss, but it's something 😁

**Comment by elbourki** [comment]
Hey Chris!
I apologize for not being able to help with 3.0, I got a bit busier in the last few weeks :(

I was thinking of replacing `intl-messageformat` with `message-format`, it's at 21.5kB compared to 29.8kB, not a huge improvement but it would reduce the library size to 28.4kB 😬
But note that they don't have the same [API](https://github.com/format-message/format-message/tree/master/packages/message-format#messageformat), we'd have to remove the _formats_ option if we ever choose to adopt this library.

Another interesting option would be [Frenchkiss.js](https://github.com/koala-interactive/frenchkiss.js), it supports ICU and it's currently at 2.7kB 😱. The way the library works is quite different and we will probably need a major rewrite to implement it, but I think it's worth it :D

**Pull request merged**
