### PR TITLE
Support nesting/linking messages

### LINKED ISSUE #27: Nested message references / linking messages
It would be great if we could use nesting on the json translation files. [Like this](https://www.i18next.com/translation-function/nesting):
```
{
    "nesting1": "1 $_(nesting2)",
    "nesting2": "2 $t(nesting3)",
    "nesting3": "3",
}
```

### PR DESCRIPTION
**Pull request by ehsanonline**
I'm not very familiar with typescript! but this might close #27
Added nesting feature to the library, with this sample usage:
```json5
//en.json
{
  "user":{
    "name":"John"
  },
  "title":"Title",
  "key.with.dots":"Value",
  
  "nested_title":"Nested {{title}}", // Nested Title
  "deep_nested_title":"Deep {{nested_title}}", // Deep Nested Title
  "multiple_nested":"{{title}} {{title}} {{nested_title}}", // Title Title Nested Title
  "deep_path_nested":"Name: {{user.name}}", // Name: John
  "nested_key_with_dots":"{{key.with.dots}}", // Value
  "empty_nested":"just me {{}}", // just me 
  "full_empty_nested":"{{}}" // ""
}
```
Note: correctly not support deep path with dotted key combination. So please avoid nesting dotted keys in a child dictionary: (only use dotted keys in main dictionary with string value)
```json5
{
  "deep" : {
    "key.with.dots":"value"
  },
  "deep.key":{
    "with.dots":"value"
  },
  "deep.key.with":{
    "dots":"value"
  },
  "nested":"{{deep.key.with.dots}}" // error
}
```

Between a dotted key and a deep path key, the priority is with the dotted key:
```json5
{
  "my.key":"Dotted key wins!",
  "my":{
    "key":"Deep path key wins!"
  },
  "nested_dotted_key_priority_check" : "{{my.key}}" // Dotted key wins!
}
```

### CODE REVIEW

**Comment by kaisermann** [comment]
Hey @ehsanonline 👋  First of all, thanks for proactively trying to implement this feature! I see that you're interpolating the linked messages at the `addMessages` method. However, there are some issues with that approach:

1.  we can't assume the whole locale dictionary will be loaded at the same `addMessages` call:

**Example scenario**:

```js
addMesssages('en', {
  yes: 'Yes',
  no: 'No',
});

// somewhere else
addMesssages('en', {
    confirmation: 'Please answer {{yes}} or {{no}}',
});
```

`confirmation` wouldn't be able to link those messages. The problem is even worse if we consider the async loading of dictionary partials via `register()`. 

2. I don't think looping through all the values of every dictionary is the best decision performance-wise. A better approach could be to lazily parse a looked up message, find its links (not sure about regexp for this, but don't have a better idea right now), interpolate them into the message and check if the performance hit is still low.

**Comment by ehsanonline** [comment]
Hi! thanks, I'm glad to help!
1. the best way for the performance and async support is to update nested messages every time new dictionary adds to the language.
 * it will check the whole `$dictionary` and update nested messages, if some of them were undefined yet, they will be kept untouched.
 * usually `addMessage` function runs when the app starts, so it runs mainly a couple of times. of course if the programmer define whole language in one-go , it will be the best.
 *  the only scenario that I'm not sure what will happen (not tested), is when a key with undefined nested message showed on the webpage (by `$t`), at this moment it will be showed like this mybe: `Hi {{undefined_nested}}` , then the async `register` or new `addMessage` runs and define the nested key. will the text update? I don't think so. because the `lookupMessage` pass a string, not a variable for svelte to update it.
so as far as I know, the global `$dictionary` store updates new nested keys as soon as they defined, but updating the text is not about nesting, and needs separate coding/issuing.
also I think it's not a good practice to define language part by part or showing before making sure about defining!

2. looking up for nested messages when a message calls is not good. imagine for every page loading and every message calling we run loops and regex! the best way is to replace nested keys with values when the app runs for one time or every time that a new dictionary gets add. 
thanks for mentioning the `lookupMessage`, I used that instead of ugly regex! only thing is that this function caches the keys, so it will cache all nested keys. maybe we need to cache only what user calls. a solution is to add a `cache=false` argument to the function. 

3. you can pass args to the nested value instead, like this: 
```json5
{
  "key":"{arg}",
  "nested":"nested {{key}}"
}
```
```js
format({ id:'nested', values: { arg:'argument value' } }) // nested argument value
```
but passing args and values to the linking message needs more complex regex. I'm thinking about something like this:
```json5
{
  "nested": " {{ key((arg1:value 1,arg2:value 2)) }} ",
  // or this with ability to add space at the end and beginning of values and between args :
  "nested": {{ key(( arg1: ' value 1' , arg2 : 'value 2 ' ))}}, 
}
```
which makes it very ugly!

**Comment by ehsanonline** [comment]
the only benefit that processing via `lookupMessage` has over `addMessages` is when a key which is used in nested messages updates: 
```js
addMessages('en',{
  key:"Hi",
  nested:"{{key}}"
})
//after that, updating `key`
addMessages('en',{
  key:"Hello"
})
// if processing nested messages in addMessage: (best performance)
lookupMessage('nested','en') // Hi
// if processing nested messages in lookupMessage every time we want to show a message: (low performance)
lookupMessage('nested','en') // Hello
```
we can add an option in `init` to set that as user like how to process it.

**Comment by kaisermann** [comment]
Sorry for taking so long to answer and thanks for being so descriptive.

> when a key with undefined nested message showed on the webpage (by $t), at this moment it will be showed like this maybe: Hi {{undefined_nested}} , then the async register or new addMessage runs and define the nested key. will the text update? 
 
The `format` method is [`derived` from the `locale` and `dictionary`](https://github.com/kaisermann/svelte-i18n/blob/master/src/client/stores/format.ts#L63) methods. Whenever one of them is updated, all localised texts will be updated.

> looking up for nested messages when a message calls is not good. imagine for every page loading and every message calling we run loops and regex! 

Found a bug regarding that, thanks! it's not caching them correctly. I'm going to try fixing it soon. But yeah, `lookupMessage` is probably not the best place to put this kind of parsing, since it doesn't necessarily have to do with the `lookup` task. We could also cache the `format` result but that would leave us with another cache (apart from the lookup and formatter caches)... not the most optimal solution 🤔

Anyway, I'm still unsure about adding new syntax over the well established ICU and these kind of complexity to the library. I can see why linking messages can be useful, but from my experience, it's not a must-have feature for the majority of cases. It would be great if you're able to elucidate me on some real-world use cases.

**Comment by ehsanonline** [comment]
Welcome back! nesting messages are very useful even for small projects. for example we can use translate json files for some static data that we always use, and we don't want to get them from back-end or database every time. like the **site or company name**. we might use it in title, in parts of texts, at the footer as copyright, etc. the **company address and phone numbers** are also the data that we want to use them in all languages the same. and when we need to change them, we can simply change the message which is nested in other messages. as the project get more complex, nesting messages become more necessary.
it helps the project to be clean and more understandable, specially for hired programmers who want to do a professional job.

**Comment by kaisermann** [comment]
Thanks 😁 

From what you described, would something akin to global interpolation values suffice? 

_imagining_ 🌈 

```js
init({
  fallbackLocale: ...,
  
```

**Comment by kaisermann** [comment]
Thanks 😁 

From what you described, would something akin to global interpolation values suffice? 

🌈 _imagining:_ 

```jsonc
// interpolations starting with @ (example only, could be any sane !@#%... character) would be automatically interpolated
{
  "copyright": "Copyright © {@companyName}",
  "phone": "Call us at {@phoneNumber}"
}
```

```js
// i18n.js
init({
  fallbackLocale: 'en',
  // with these values, which can be imported from another file
  globalInterpolationValues: {
    companyName: 'BitPeckish',
    phoneNumber: '+55 24 99120-0120',
  },
})
```

**Comment by ehsanonline** [comment]
It doesn't cover the full use case of nesting, for example the company name might change in different languages. 
Also for none-English languages like Persian as a RTL (right to left) language, we don't want to write Persian words in our code file to make it messy. changing a RTL word among English words in code editors becomes difficult as well. we want all the texts to be in one place. it will help the person who want to translate them too.

**Comment by kaisermann** [comment]
As this didn't raise much interest and it's possible to do it, albeit, with a bit of verbosity, I won't go through with this.

**Pull request closed without merging**
